### ISSUE TITLE
Контакти для спілкування

### ISSUE THREAD

**Issue by VSydorenko** [new-era-uk/scope#3]
Готовий прийняти участь в розробці рішення як аналітик. Як з вами можна зв'язуватись для обговорень? Може, є група в Телеграмі?

**Comment by alex-kukhtin** [comment]
Пишіть в особисті Dmytro Saltovets. Він у нас за координацію відповідає.

https://www.facebook.com/groups/269959381075647/user/100004620152226/

Якщо є ідеї / документи - краще за все прямо сюди викладати. Можна я окремі issue.
Будемо опрацьвувати та додавати в доку. Щоб з'являлось прямо тут.

https://new-era-uk.github.io/scope/

Ще можна самостійно форкнути і закидувати Pull Request'и.
